name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: www/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: www
      - name: Build website
        run: npm run build
        working-directory: www
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www/build
          cname: monorise.github.io
